<!-- script type="text/javascript" src="/MyScript.js"></script-->
<!--<script type="text/javascript" src="/Excel.js"></script>-->
<?php //echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/dropkick.css'); ?>
<?php //echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/blank_theme.css'); ?>
<script type="text/javascript" src="/Trial.js"></script>


<div id="fb-root"></div>

<noscript><h1 style="color: red;">Your Browser's javascript option is disabled,Please enable it</h1></noscript>
<div  align="center">
<input name="" id="trial" name="trial"/>
<div id="Error"></div>
<input name="" id="newButton" type="button" onclick="test();" value="Button" title=""/>


</div>
